[package]
name = "venus"
version = "0.1.0"
authors = ["sagan <camjanssen120@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "1.3.0"
chrono = "0.4.13"
serde_json = "1.0.57"
colored = "2.0.0"
